/**
 * The rules behind the trending numbers, with no file system or jscpd in
 * them: what counts as code, how clone pairs become findings, how a path is
 * classified, and the calendar helpers. trending-scan.mjs applies them while
 * measuring, trending-lib.mjs while deriving the site's data files.
 */

export const round2 = (n) => typeof n === 'number' ? Math.round(n * 100) / 100 : n

// A repository with fewer code files than this gets no code percentage on
// the pages: one copied file would swing it by tens of points.
export const MIN_CODE_FILES = 20

// The raw scan: what the archive has measured since 2026-09-01.
export const ALL_IGNORE = [
  '**/node_modules/**', '**/vendor/**', '**/third_party/**', '**/dist/**', '**/build/**',
  '**/*.min.js', '**/*.map', '**/package-lock.json', '**/pnpm-lock.yaml'
]

// Programming-language formats, by the names `jscpd --list` prints. Markup,
// styles, data, config, text, diagrams and templates stay out: duplication
// there says nothing about how the program is written. Formats registered
// without a file extension (abap, cobol, glsl, ...) would never match a file
// anyway, so they are not listed.
export const CODE_FORMATS = [
  'actionscript', 'ada', 'apex', 'apl', 'astro', 'awk', 'bash', 'basic', 'c', 'c-header', 'cfml', 'cfscript',
  'clojure', 'coffeescript', 'cpp', 'cpp-header', 'crystal', 'csharp', 'd', 'dart', 'eiffel', 'elm', 'erlang',
  'fortran', 'fsharp', 'gdscript', 'go', 'groovy', 'haskell', 'haxe', 'idris', 'java', 'javascript', 'jsx',
  'julia', 'kotlin', 'lisp', 'livescript', 'lua', 'objectivec', 'ocaml', 'oz', 'pascal', 'perl', 'php', 'plsql',
  'powershell', 'prolog', 'purescript', 'python', 'q', 'qsharp', 'r', 'racket', 'rescript', 'ruby', 'rust',
  'sas', 'scala', 'scheme', 'smalltalk', 'solidity', 'sql', 'svelte', 'swift', 'tcl', 'tsx', 'typescript',
  'unrealscript', 'vbnet', 'verilog', 'vhdl', 'vue', 'wgsl', 'wolfram', 'zig'
]

// What does not count as the repository's own code. jscpd matches these
// against the path inside the scanned tree.
export const CODE_IGNORE = [
  // dependencies and vendored code
  '**/node_modules/**', '**/bower_components/**', '**/.yarn/**', '**/vendor/**', '**/vendors/**',
  '**/third_party/**', '**/thirdparty/**', '**/3rdparty/**', '**/external/**', '**/externals/**',
  // build output and caches
  '**/dist/**', '**/target/**', '**/.next/**', '**/.nuxt/**', '**/.output/**', '**/__pycache__/**',
  '**/*.min.js', '**/*.min.css', '**/*.bundle.js', '**/*.map',
  // tests, fixtures, snapshots and mocks
  '**/test/**', '**/tests/**', '**/__tests__/**', '**/spec/**', '**/specs/**', '**/testdata/**',
  '**/test_data/**', '**/testing/**', '**/fixtures/**', '**/fixture/**', '**/__fixtures__/**',
  '**/__snapshots__/**', '**/snapshots/**', '**/__mocks__/**', '**/mocks/**', '**/e2e/**',
  '**/*.test.*', '**/*.spec.*', '**/*_test.go', '**/*_test.py', '**/test_*.py', '**/*Test.java',
  '**/*Tests.java', '**/*Test.kt', '**/*Tests.cs', '**/*_spec.rb', '**/*.snap',
  // documentation, examples and demos
  '**/docs/**', '**/doc/**', '**/examples/**', '**/example/**', '**/samples/**', '**/sample/**',
  '**/demo/**', '**/demos/**',
  // generated code recognisable by name (file headers are checked separately)
  '**/*.d.ts', '**/*.pb.go', '**/*_pb2.py', '**/*_pb2_grpc.py', '**/*.pb.cc', '**/*.pb.h', '**/*_pb.js',
  '**/*.g.dart', '**/*.freezed.dart', '**/*.g.cs', '**/*.designer.cs', '**/*.generated.*', '**/*.gen.go',
  '**/*.gen.ts', '**/generated/**', '**/__generated__/**', '**/migrations/**', '**/parser.c',
  '**/*.tab.c', '**/lex.yy.c',
  // translations
  '**/locales/**', '**/locale/**', '**/i18n/**', '**/translations/**', '**/*.po', '**/*.pot',
  // lockfiles
  '**/*.lock', '**/package-lock.json', '**/pnpm-lock.yaml', '**/yarn.lock'
]

// Generated code announces itself in a header comment. Only comment lines
// count: the generator's own source carries the same words inside a string
// literal, and prose like "the key will be overwritten" sits in ordinary
// comments, so the phrases below are the ones that only generators write.
export const GENERATED_HEADER = /@generated\b|do not (edit|modify)|code generated by|automatically generated|auto[- ]?generated|this file (is|was) generated|machine[- ]generated|changes (made in this file )?will be (lost|overwritten)/i
export const COMMENT_LINE = /^\s*(\/\/|\/\*+|\*|#|--|;|%|<!--|\(\*|\{-|"""|''')/

/** The jscpd config of the code scan, as written to disk for -c. */
export function codeScanConfig(generatedFiles = []) {
  // Exact paths are globs too; the leading **/ makes them match the path
  // inside the scanned tree whatever the tree's own location is.
  const generated = generatedFiles
    .filter(path => !/[*?[\]{}]/.test(path))
    .map(path => `**/${path}`)
  return { format: CODE_FORMATS, ignore: [...CODE_IGNORE, ...generated] }
}

/**
 * One entry per duplicated fragment. jscpd pairs every later copy with the
 * first one it saw, so pairs sharing a first fragment are one fragment copied
 * `copies` times; listing the pairs made the same block show up ten times.
 * Sorted by the duplicated volume a fix would remove. Accepts jscpd's
 * duplicates (firstFile/secondFile) and already-grouped entries alike, so
 * snapshots from before the grouping are read the same way.
 */
export function groupClones(entries, strip = p => p) {
  const groups = new Map()
  const loc = (f) => ({ name: strip(f.name), start: f.start, end: f.end })
  for (const d of entries) {
    const first = d.firstFile ? loc(d.firstFile) : d.first
    const others = d.firstFile ? [loc(d.secondFile)] : d.others
    const key = `${first.name}:${first.start}-${first.end}`
    const group = groups.get(key) || {
      format: d.format, lines: d.lines, tokens: d.tokens, first, others: [], copies: 1, fragment: d.fragment,
      ...(d.excerpt ? { excerpt: d.excerpt } : {}), ...(d.excerptSecond ? { excerptSecond: d.excerptSecond } : {})
    }
    group.others.push(...others)
    group.copies += d.firstFile ? 1 : d.copies - 1
    groups.set(key, group)
  }
  return [...groups.values()]
    .sort((a, b) => b.tokens * (b.copies - 1) - a.tokens * (a.copies - 1) || b.tokens - a.tokens)
}

// What kind of file a duplicated block lives in, from its path. The code
// scan already leaves most of these out; the raw scan's findings carry the
// label so a reader can tell a copied fixture from copied logic.
const PATH_KINDS = [
  ['vendored', /(^|\/)(vendor|vendors|third_party|thirdparty|3rdparty|node_modules|external|externals|bower_components)(\/|$)/],
  ['generated', /\.d\.ts$|\.pb\.(go|cc|h)$|_pb2(_grpc)?\.py$|_pb\.js$|\.g\.(dart|cs)$|\.freezed\.dart$|\.designer\.cs$|\.generated\.|\.gen\.(go|ts)$|(^|\/)(generated|__generated__|migrations)(\/|$)|\.min\.(js|css)$|(^|\/)(parser|lex\.yy)\.c$|\.tab\.c$/],
  ['tests', /(^|\/)(tests?|__tests__|specs?|testdata|test_data|testing|fixtures?|__fixtures__|__snapshots__|snapshots|__mocks__|mocks|e2e)(\/|$)|\.(test|spec)\.|_test\.(go|py)$|(^|\/)test_[^/]*\.py$|Tests?\.(java|kt|cs)$|_spec\.rb$|\.snap$/],
  ['translations', /(^|\/)(locales?|i18n|translations)(\/|$)|\.pot?$/],
  ['docs', /\.(md|mdx|rst|txt|adoc|asciidoc)(:|$)|(^|\/)(docs?|examples?|samples?|demos?)(\/|$)/],
  ['data', /\.(json|json5|ya?ml|toml|xml|csv|tsv|ini|properties|plist|lock|proto|graphql|gql)(:|$)/],
  ['styles', /\.(css|scss|sass|less|styl)(:|$)/],
  ['markup', /\.(html?|xhtml|svg|hbs|handlebars|pug|jade|ejs|njk|twig|liquid|mustache)(:|$)/]
]

export function classifyPath(path) {
  for (const [kind, re] of PATH_KINDS) if (re.test(path)) return kind
  return 'code'
}

/** Whether a repo's code scan is wide enough to quote a percentage for. */
export const hasCodeMetric = (repo) =>
  typeof repo?.code?.percentage === 'number' && repo.code.sources >= MIN_CODE_FILES

/** ISO week of a UTC calendar day: "2026-10-06" → "2026-W41". */
export function isoWeek(date) {
  const d = new Date(`${date}T00:00:00Z`)
  const day = d.getUTCDay() || 7
  // move to the Thursday of this week; its year is the ISO year
  d.setUTCDate(d.getUTCDate() + 4 - day)
  const yearStart = Date.UTC(d.getUTCFullYear(), 0, 1)
  const week = Math.ceil(((d - yearStart) / 86_400_000 + 1) / 7)
  return `${d.getUTCFullYear()}-W${String(week).padStart(2, '0')}`
}

/** Monday and Sunday of an ISO week, as UTC calendar days. */
export function isoWeekRange(week) {
  const [year, w] = week.split('-W').map(Number)
  // 4 January is always in week 1
  const jan4 = new Date(Date.UTC(year, 0, 4))
  const monday1 = new Date(jan4)
  monday1.setUTCDate(jan4.getUTCDate() - ((jan4.getUTCDay() || 7) - 1))
  const from = new Date(monday1)
  from.setUTCDate(monday1.getUTCDate() + (w - 1) * 7)
  const to = new Date(from)
  to.setUTCDate(from.getUTCDate() + 6)
  return { from: from.toISOString().slice(0, 10), to: to.toISOString().slice(0, 10) }
}

/** Linear-interpolated percentile of a sorted numeric array (0..100). */
export function percentile(sorted, p) {
  if (sorted.length === 0) return null
  const pos = (sorted.length - 1) * p / 100
  const lo = Math.floor(pos)
  const hi = Math.ceil(pos)
  return round2(sorted[lo] + (sorted[hi] - sorted[lo]) * (pos - lo))
}
